#ifndef APATE_CONSTANTS_H
#define APATE_CONSTANTS_H

#define RESULT_SUCCESS  0
#define RESULT_UNKNOWN 1
#define RESULT_FAILURE 2

#define COUNT_OVER_LAST_X_DAYS 7
#define MIN_NB_DURING_LAST_X_DAYS 1000

#endif //APATE_CONSTANTS_H
