# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/888/bin/cmake

# The command to remove a file.
RM = /snap/cmake/888/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/CLionProjects/apate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/CLionProjects/apate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/888/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/888/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/CLionProjects/apate/CMakeFiles /home/victor/CLionProjects/apate//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/CLionProjects/apate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named apate

# Build rule for target.
apate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 apate
.PHONY : apate

# fast build rule for target.
apate/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/build
.PHONY : apate/fast

antiDebug/debugmenot.o: antiDebug/debugmenot.c.o
.PHONY : antiDebug/debugmenot.o

# target to build an object file
antiDebug/debugmenot.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/debugmenot.c.o
.PHONY : antiDebug/debugmenot.c.o

antiDebug/debugmenot.i: antiDebug/debugmenot.c.i
.PHONY : antiDebug/debugmenot.i

# target to preprocess a source file
antiDebug/debugmenot.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/debugmenot.c.i
.PHONY : antiDebug/debugmenot.c.i

antiDebug/debugmenot.s: antiDebug/debugmenot.c.s
.PHONY : antiDebug/debugmenot.s

# target to generate assembly for a file
antiDebug/debugmenot.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/debugmenot.c.s
.PHONY : antiDebug/debugmenot.c.s

antiDebug/test_env.o: antiDebug/test_env.c.o
.PHONY : antiDebug/test_env.o

# target to build an object file
antiDebug/test_env.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_env.c.o
.PHONY : antiDebug/test_env.c.o

antiDebug/test_env.i: antiDebug/test_env.c.i
.PHONY : antiDebug/test_env.i

# target to preprocess a source file
antiDebug/test_env.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_env.c.i
.PHONY : antiDebug/test_env.c.i

antiDebug/test_env.s: antiDebug/test_env.c.s
.PHONY : antiDebug/test_env.s

# target to generate assembly for a file
antiDebug/test_env.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_env.c.s
.PHONY : antiDebug/test_env.c.s

antiDebug/test_ldhook.o: antiDebug/test_ldhook.c.o
.PHONY : antiDebug/test_ldhook.o

# target to build an object file
antiDebug/test_ldhook.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ldhook.c.o
.PHONY : antiDebug/test_ldhook.c.o

antiDebug/test_ldhook.i: antiDebug/test_ldhook.c.i
.PHONY : antiDebug/test_ldhook.i

# target to preprocess a source file
antiDebug/test_ldhook.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ldhook.c.i
.PHONY : antiDebug/test_ldhook.c.i

antiDebug/test_ldhook.s: antiDebug/test_ldhook.c.s
.PHONY : antiDebug/test_ldhook.s

# target to generate assembly for a file
antiDebug/test_ldhook.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ldhook.c.s
.PHONY : antiDebug/test_ldhook.c.s

antiDebug/test_nearheap.o: antiDebug/test_nearheap.c.o
.PHONY : antiDebug/test_nearheap.o

# target to build an object file
antiDebug/test_nearheap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_nearheap.c.o
.PHONY : antiDebug/test_nearheap.c.o

antiDebug/test_nearheap.i: antiDebug/test_nearheap.c.i
.PHONY : antiDebug/test_nearheap.i

# target to preprocess a source file
antiDebug/test_nearheap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_nearheap.c.i
.PHONY : antiDebug/test_nearheap.c.i

antiDebug/test_nearheap.s: antiDebug/test_nearheap.c.s
.PHONY : antiDebug/test_nearheap.s

# target to generate assembly for a file
antiDebug/test_nearheap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_nearheap.c.s
.PHONY : antiDebug/test_nearheap.c.s

antiDebug/test_noaslr.o: antiDebug/test_noaslr.c.o
.PHONY : antiDebug/test_noaslr.o

# target to build an object file
antiDebug/test_noaslr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_noaslr.c.o
.PHONY : antiDebug/test_noaslr.c.o

antiDebug/test_noaslr.i: antiDebug/test_noaslr.c.i
.PHONY : antiDebug/test_noaslr.i

# target to preprocess a source file
antiDebug/test_noaslr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_noaslr.c.i
.PHONY : antiDebug/test_noaslr.c.i

antiDebug/test_noaslr.s: antiDebug/test_noaslr.c.s
.PHONY : antiDebug/test_noaslr.s

# target to generate assembly for a file
antiDebug/test_noaslr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_noaslr.c.s
.PHONY : antiDebug/test_noaslr.c.s

antiDebug/test_parent.o: antiDebug/test_parent.c.o
.PHONY : antiDebug/test_parent.o

# target to build an object file
antiDebug/test_parent.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_parent.c.o
.PHONY : antiDebug/test_parent.c.o

antiDebug/test_parent.i: antiDebug/test_parent.c.i
.PHONY : antiDebug/test_parent.i

# target to preprocess a source file
antiDebug/test_parent.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_parent.c.i
.PHONY : antiDebug/test_parent.c.i

antiDebug/test_parent.s: antiDebug/test_parent.c.s
.PHONY : antiDebug/test_parent.s

# target to generate assembly for a file
antiDebug/test_parent.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_parent.c.s
.PHONY : antiDebug/test_parent.c.s

antiDebug/test_ptrace.o: antiDebug/test_ptrace.c.o
.PHONY : antiDebug/test_ptrace.o

# target to build an object file
antiDebug/test_ptrace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ptrace.c.o
.PHONY : antiDebug/test_ptrace.c.o

antiDebug/test_ptrace.i: antiDebug/test_ptrace.c.i
.PHONY : antiDebug/test_ptrace.i

# target to preprocess a source file
antiDebug/test_ptrace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ptrace.c.i
.PHONY : antiDebug/test_ptrace.c.i

antiDebug/test_ptrace.s: antiDebug/test_ptrace.c.s
.PHONY : antiDebug/test_ptrace.s

# target to generate assembly for a file
antiDebug/test_ptrace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_ptrace.c.s
.PHONY : antiDebug/test_ptrace.c.s

antiDebug/test_vdso.o: antiDebug/test_vdso.c.o
.PHONY : antiDebug/test_vdso.o

# target to build an object file
antiDebug/test_vdso.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_vdso.c.o
.PHONY : antiDebug/test_vdso.c.o

antiDebug/test_vdso.i: antiDebug/test_vdso.c.i
.PHONY : antiDebug/test_vdso.i

# target to preprocess a source file
antiDebug/test_vdso.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_vdso.c.i
.PHONY : antiDebug/test_vdso.c.i

antiDebug/test_vdso.s: antiDebug/test_vdso.c.s
.PHONY : antiDebug/test_vdso.s

# target to generate assembly for a file
antiDebug/test_vdso.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiDebug/test_vdso.c.s
.PHONY : antiDebug/test_vdso.c.s

antiSandbox/browserHistory.o: antiSandbox/browserHistory.c.o
.PHONY : antiSandbox/browserHistory.o

# target to build an object file
antiSandbox/browserHistory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/browserHistory.c.o
.PHONY : antiSandbox/browserHistory.c.o

antiSandbox/browserHistory.i: antiSandbox/browserHistory.c.i
.PHONY : antiSandbox/browserHistory.i

# target to preprocess a source file
antiSandbox/browserHistory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/browserHistory.c.i
.PHONY : antiSandbox/browserHistory.c.i

antiSandbox/browserHistory.s: antiSandbox/browserHistory.c.s
.PHONY : antiSandbox/browserHistory.s

# target to generate assembly for a file
antiSandbox/browserHistory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/browserHistory.c.s
.PHONY : antiSandbox/browserHistory.c.s

antiSandbox/chromeHistory.o: antiSandbox/chromeHistory.c.o
.PHONY : antiSandbox/chromeHistory.o

# target to build an object file
antiSandbox/chromeHistory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/chromeHistory.c.o
.PHONY : antiSandbox/chromeHistory.c.o

antiSandbox/chromeHistory.i: antiSandbox/chromeHistory.c.i
.PHONY : antiSandbox/chromeHistory.i

# target to preprocess a source file
antiSandbox/chromeHistory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/chromeHistory.c.i
.PHONY : antiSandbox/chromeHistory.c.i

antiSandbox/chromeHistory.s: antiSandbox/chromeHistory.c.s
.PHONY : antiSandbox/chromeHistory.s

# target to generate assembly for a file
antiSandbox/chromeHistory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/chromeHistory.c.s
.PHONY : antiSandbox/chromeHistory.c.s

antiSandbox/firefoxHistory.o: antiSandbox/firefoxHistory.c.o
.PHONY : antiSandbox/firefoxHistory.o

# target to build an object file
antiSandbox/firefoxHistory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/firefoxHistory.c.o
.PHONY : antiSandbox/firefoxHistory.c.o

antiSandbox/firefoxHistory.i: antiSandbox/firefoxHistory.c.i
.PHONY : antiSandbox/firefoxHistory.i

# target to preprocess a source file
antiSandbox/firefoxHistory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/firefoxHistory.c.i
.PHONY : antiSandbox/firefoxHistory.c.i

antiSandbox/firefoxHistory.s: antiSandbox/firefoxHistory.c.s
.PHONY : antiSandbox/firefoxHistory.s

# target to generate assembly for a file
antiSandbox/firefoxHistory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/firefoxHistory.c.s
.PHONY : antiSandbox/firefoxHistory.c.s

antiSandbox/upTime.o: antiSandbox/upTime.c.o
.PHONY : antiSandbox/upTime.o

# target to build an object file
antiSandbox/upTime.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/upTime.c.o
.PHONY : antiSandbox/upTime.c.o

antiSandbox/upTime.i: antiSandbox/upTime.c.i
.PHONY : antiSandbox/upTime.i

# target to preprocess a source file
antiSandbox/upTime.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/upTime.c.i
.PHONY : antiSandbox/upTime.c.i

antiSandbox/upTime.s: antiSandbox/upTime.c.s
.PHONY : antiSandbox/upTime.s

# target to generate assembly for a file
antiSandbox/upTime.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiSandbox/upTime.c.s
.PHONY : antiSandbox/upTime.c.s

antiVM/biosVendor.o: antiVM/biosVendor.c.o
.PHONY : antiVM/biosVendor.o

# target to build an object file
antiVM/biosVendor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/biosVendor.c.o
.PHONY : antiVM/biosVendor.c.o

antiVM/biosVendor.i: antiVM/biosVendor.c.i
.PHONY : antiVM/biosVendor.i

# target to preprocess a source file
antiVM/biosVendor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/biosVendor.c.i
.PHONY : antiVM/biosVendor.c.i

antiVM/biosVendor.s: antiVM/biosVendor.c.s
.PHONY : antiVM/biosVendor.s

# target to generate assembly for a file
antiVM/biosVendor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/biosVendor.c.s
.PHONY : antiVM/biosVendor.c.s

antiVM/boardVendor.o: antiVM/boardVendor.c.o
.PHONY : antiVM/boardVendor.o

# target to build an object file
antiVM/boardVendor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/boardVendor.c.o
.PHONY : antiVM/boardVendor.c.o

antiVM/boardVendor.i: antiVM/boardVendor.c.i
.PHONY : antiVM/boardVendor.i

# target to preprocess a source file
antiVM/boardVendor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/boardVendor.c.i
.PHONY : antiVM/boardVendor.c.i

antiVM/boardVendor.s: antiVM/boardVendor.c.s
.PHONY : antiVM/boardVendor.s

# target to generate assembly for a file
antiVM/boardVendor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/boardVendor.c.s
.PHONY : antiVM/boardVendor.c.s

antiVM/devicesScsi.o: antiVM/devicesScsi.c.o
.PHONY : antiVM/devicesScsi.o

# target to build an object file
antiVM/devicesScsi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/devicesScsi.c.o
.PHONY : antiVM/devicesScsi.c.o

antiVM/devicesScsi.i: antiVM/devicesScsi.c.i
.PHONY : antiVM/devicesScsi.i

# target to preprocess a source file
antiVM/devicesScsi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/devicesScsi.c.i
.PHONY : antiVM/devicesScsi.c.i

antiVM/devicesScsi.s: antiVM/devicesScsi.c.s
.PHONY : antiVM/devicesScsi.s

# target to generate assembly for a file
antiVM/devicesScsi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/devicesScsi.c.s
.PHONY : antiVM/devicesScsi.c.s

antiVM/fileSystemSpace.o: antiVM/fileSystemSpace.c.o
.PHONY : antiVM/fileSystemSpace.o

# target to build an object file
antiVM/fileSystemSpace.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/fileSystemSpace.c.o
.PHONY : antiVM/fileSystemSpace.c.o

antiVM/fileSystemSpace.i: antiVM/fileSystemSpace.c.i
.PHONY : antiVM/fileSystemSpace.i

# target to preprocess a source file
antiVM/fileSystemSpace.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/fileSystemSpace.c.i
.PHONY : antiVM/fileSystemSpace.c.i

antiVM/fileSystemSpace.s: antiVM/fileSystemSpace.c.s
.PHONY : antiVM/fileSystemSpace.s

# target to generate assembly for a file
antiVM/fileSystemSpace.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/fileSystemSpace.c.s
.PHONY : antiVM/fileSystemSpace.c.s

antiVM/hypervisorFlag.o: antiVM/hypervisorFlag.c.o
.PHONY : antiVM/hypervisorFlag.o

# target to build an object file
antiVM/hypervisorFlag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/hypervisorFlag.c.o
.PHONY : antiVM/hypervisorFlag.c.o

antiVM/hypervisorFlag.i: antiVM/hypervisorFlag.c.i
.PHONY : antiVM/hypervisorFlag.i

# target to preprocess a source file
antiVM/hypervisorFlag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/hypervisorFlag.c.i
.PHONY : antiVM/hypervisorFlag.c.i

antiVM/hypervisorFlag.s: antiVM/hypervisorFlag.c.s
.PHONY : antiVM/hypervisorFlag.s

# target to generate assembly for a file
antiVM/hypervisorFlag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/hypervisorFlag.c.s
.PHONY : antiVM/hypervisorFlag.c.s

antiVM/loadedModulesFromLSMOD.o: antiVM/loadedModulesFromLSMOD.c.o
.PHONY : antiVM/loadedModulesFromLSMOD.o

# target to build an object file
antiVM/loadedModulesFromLSMOD.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/loadedModulesFromLSMOD.c.o
.PHONY : antiVM/loadedModulesFromLSMOD.c.o

antiVM/loadedModulesFromLSMOD.i: antiVM/loadedModulesFromLSMOD.c.i
.PHONY : antiVM/loadedModulesFromLSMOD.i

# target to preprocess a source file
antiVM/loadedModulesFromLSMOD.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/loadedModulesFromLSMOD.c.i
.PHONY : antiVM/loadedModulesFromLSMOD.c.i

antiVM/loadedModulesFromLSMOD.s: antiVM/loadedModulesFromLSMOD.c.s
.PHONY : antiVM/loadedModulesFromLSMOD.s

# target to generate assembly for a file
antiVM/loadedModulesFromLSMOD.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/loadedModulesFromLSMOD.c.s
.PHONY : antiVM/loadedModulesFromLSMOD.c.s

antiVM/macAddress.o: antiVM/macAddress.c.o
.PHONY : antiVM/macAddress.o

# target to build an object file
antiVM/macAddress.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/macAddress.c.o
.PHONY : antiVM/macAddress.c.o

antiVM/macAddress.i: antiVM/macAddress.c.i
.PHONY : antiVM/macAddress.i

# target to preprocess a source file
antiVM/macAddress.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/macAddress.c.i
.PHONY : antiVM/macAddress.c.i

antiVM/macAddress.s: antiVM/macAddress.c.s
.PHONY : antiVM/macAddress.s

# target to generate assembly for a file
antiVM/macAddress.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/macAddress.c.s
.PHONY : antiVM/macAddress.c.s

antiVM/productName.o: antiVM/productName.c.o
.PHONY : antiVM/productName.o

# target to build an object file
antiVM/productName.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/productName.c.o
.PHONY : antiVM/productName.c.o

antiVM/productName.i: antiVM/productName.c.i
.PHONY : antiVM/productName.i

# target to preprocess a source file
antiVM/productName.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/productName.c.i
.PHONY : antiVM/productName.c.i

antiVM/productName.s: antiVM/productName.c.s
.PHONY : antiVM/productName.s

# target to generate assembly for a file
antiVM/productName.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/productName.c.s
.PHONY : antiVM/productName.c.s

antiVM/ramSize.o: antiVM/ramSize.c.o
.PHONY : antiVM/ramSize.o

# target to build an object file
antiVM/ramSize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/ramSize.c.o
.PHONY : antiVM/ramSize.c.o

antiVM/ramSize.i: antiVM/ramSize.c.i
.PHONY : antiVM/ramSize.i

# target to preprocess a source file
antiVM/ramSize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/ramSize.c.i
.PHONY : antiVM/ramSize.c.i

antiVM/ramSize.s: antiVM/ramSize.c.s
.PHONY : antiVM/ramSize.s

# target to generate assembly for a file
antiVM/ramSize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/ramSize.c.s
.PHONY : antiVM/ramSize.c.s

antiVM/screenResolution.o: antiVM/screenResolution.c.o
.PHONY : antiVM/screenResolution.o

# target to build an object file
antiVM/screenResolution.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/screenResolution.c.o
.PHONY : antiVM/screenResolution.c.o

antiVM/screenResolution.i: antiVM/screenResolution.c.i
.PHONY : antiVM/screenResolution.i

# target to preprocess a source file
antiVM/screenResolution.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/screenResolution.c.i
.PHONY : antiVM/screenResolution.c.i

antiVM/screenResolution.s: antiVM/screenResolution.c.s
.PHONY : antiVM/screenResolution.s

# target to generate assembly for a file
antiVM/screenResolution.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/screenResolution.c.s
.PHONY : antiVM/screenResolution.c.s

antiVM/systemAge.o: antiVM/systemAge.c.o
.PHONY : antiVM/systemAge.o

# target to build an object file
antiVM/systemAge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemAge.c.o
.PHONY : antiVM/systemAge.c.o

antiVM/systemAge.i: antiVM/systemAge.c.i
.PHONY : antiVM/systemAge.i

# target to preprocess a source file
antiVM/systemAge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemAge.c.i
.PHONY : antiVM/systemAge.c.i

antiVM/systemAge.s: antiVM/systemAge.c.s
.PHONY : antiVM/systemAge.s

# target to generate assembly for a file
antiVM/systemAge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemAge.c.s
.PHONY : antiVM/systemAge.c.s

antiVM/systemVendor.o: antiVM/systemVendor.c.o
.PHONY : antiVM/systemVendor.o

# target to build an object file
antiVM/systemVendor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemVendor.c.o
.PHONY : antiVM/systemVendor.c.o

antiVM/systemVendor.i: antiVM/systemVendor.c.i
.PHONY : antiVM/systemVendor.i

# target to preprocess a source file
antiVM/systemVendor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemVendor.c.i
.PHONY : antiVM/systemVendor.c.i

antiVM/systemVendor.s: antiVM/systemVendor.c.s
.PHONY : antiVM/systemVendor.s

# target to generate assembly for a file
antiVM/systemVendor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/systemVendor.c.s
.PHONY : antiVM/systemVendor.c.s

antiVM/userNames.o: antiVM/userNames.c.o
.PHONY : antiVM/userNames.o

# target to build an object file
antiVM/userNames.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/userNames.c.o
.PHONY : antiVM/userNames.c.o

antiVM/userNames.i: antiVM/userNames.c.i
.PHONY : antiVM/userNames.i

# target to preprocess a source file
antiVM/userNames.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/userNames.c.i
.PHONY : antiVM/userNames.c.i

antiVM/userNames.s: antiVM/userNames.c.s
.PHONY : antiVM/userNames.s

# target to generate assembly for a file
antiVM/userNames.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/antiVM/userNames.c.s
.PHONY : antiVM/userNames.c.s

consoleManager.o: consoleManager.c.o
.PHONY : consoleManager.o

# target to build an object file
consoleManager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/consoleManager.c.o
.PHONY : consoleManager.c.o

consoleManager.i: consoleManager.c.i
.PHONY : consoleManager.i

# target to preprocess a source file
consoleManager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/consoleManager.c.i
.PHONY : consoleManager.c.i

consoleManager.s: consoleManager.c.s
.PHONY : consoleManager.s

# target to generate assembly for a file
consoleManager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/consoleManager.c.s
.PHONY : consoleManager.c.s

files.o: files.c.o
.PHONY : files.o

# target to build an object file
files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/files.c.o
.PHONY : files.c.o

files.i: files.c.i
.PHONY : files.i

# target to preprocess a source file
files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/files.c.i
.PHONY : files.c.i

files.s: files.c.s
.PHONY : files.s

# target to generate assembly for a file
files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/files.c.s
.PHONY : files.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/apate.dir/build.make CMakeFiles/apate.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... apate"
	@echo "... antiDebug/debugmenot.o"
	@echo "... antiDebug/debugmenot.i"
	@echo "... antiDebug/debugmenot.s"
	@echo "... antiDebug/test_env.o"
	@echo "... antiDebug/test_env.i"
	@echo "... antiDebug/test_env.s"
	@echo "... antiDebug/test_ldhook.o"
	@echo "... antiDebug/test_ldhook.i"
	@echo "... antiDebug/test_ldhook.s"
	@echo "... antiDebug/test_nearheap.o"
	@echo "... antiDebug/test_nearheap.i"
	@echo "... antiDebug/test_nearheap.s"
	@echo "... antiDebug/test_noaslr.o"
	@echo "... antiDebug/test_noaslr.i"
	@echo "... antiDebug/test_noaslr.s"
	@echo "... antiDebug/test_parent.o"
	@echo "... antiDebug/test_parent.i"
	@echo "... antiDebug/test_parent.s"
	@echo "... antiDebug/test_ptrace.o"
	@echo "... antiDebug/test_ptrace.i"
	@echo "... antiDebug/test_ptrace.s"
	@echo "... antiDebug/test_vdso.o"
	@echo "... antiDebug/test_vdso.i"
	@echo "... antiDebug/test_vdso.s"
	@echo "... antiSandbox/browserHistory.o"
	@echo "... antiSandbox/browserHistory.i"
	@echo "... antiSandbox/browserHistory.s"
	@echo "... antiSandbox/chromeHistory.o"
	@echo "... antiSandbox/chromeHistory.i"
	@echo "... antiSandbox/chromeHistory.s"
	@echo "... antiSandbox/firefoxHistory.o"
	@echo "... antiSandbox/firefoxHistory.i"
	@echo "... antiSandbox/firefoxHistory.s"
	@echo "... antiSandbox/upTime.o"
	@echo "... antiSandbox/upTime.i"
	@echo "... antiSandbox/upTime.s"
	@echo "... antiVM/biosVendor.o"
	@echo "... antiVM/biosVendor.i"
	@echo "... antiVM/biosVendor.s"
	@echo "... antiVM/boardVendor.o"
	@echo "... antiVM/boardVendor.i"
	@echo "... antiVM/boardVendor.s"
	@echo "... antiVM/devicesScsi.o"
	@echo "... antiVM/devicesScsi.i"
	@echo "... antiVM/devicesScsi.s"
	@echo "... antiVM/fileSystemSpace.o"
	@echo "... antiVM/fileSystemSpace.i"
	@echo "... antiVM/fileSystemSpace.s"
	@echo "... antiVM/hypervisorFlag.o"
	@echo "... antiVM/hypervisorFlag.i"
	@echo "... antiVM/hypervisorFlag.s"
	@echo "... antiVM/loadedModulesFromLSMOD.o"
	@echo "... antiVM/loadedModulesFromLSMOD.i"
	@echo "... antiVM/loadedModulesFromLSMOD.s"
	@echo "... antiVM/macAddress.o"
	@echo "... antiVM/macAddress.i"
	@echo "... antiVM/macAddress.s"
	@echo "... antiVM/productName.o"
	@echo "... antiVM/productName.i"
	@echo "... antiVM/productName.s"
	@echo "... antiVM/ramSize.o"
	@echo "... antiVM/ramSize.i"
	@echo "... antiVM/ramSize.s"
	@echo "... antiVM/screenResolution.o"
	@echo "... antiVM/screenResolution.i"
	@echo "... antiVM/screenResolution.s"
	@echo "... antiVM/systemAge.o"
	@echo "... antiVM/systemAge.i"
	@echo "... antiVM/systemAge.s"
	@echo "... antiVM/systemVendor.o"
	@echo "... antiVM/systemVendor.i"
	@echo "... antiVM/systemVendor.s"
	@echo "... antiVM/userNames.o"
	@echo "... antiVM/userNames.i"
	@echo "... antiVM/userNames.s"
	@echo "... consoleManager.o"
	@echo "... consoleManager.i"
	@echo "... consoleManager.s"
	@echo "... files.o"
	@echo "... files.i"
	@echo "... files.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

